
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import java.awt.event.*;
import java.beans.*;

import javax.swing.*;

public class MyElement extends javax.swing.JPanel implements BeanInfo
{
    private String StaticText = "Static text", list1[] = {"empty"}, list2[] = {"empty"};

    private char commandKey = 'z';

    public void setStaticText(String staticText)
    {
        this.StaticText = staticText;
    }

    public void setList1(String[] list1)
    {
        this.list1 = list1;
    }

    public void setList2(String[] list2)
    {
        this.list2 = list2;
    }

    public void setCommandKey(char commandKey)
    {
        this.commandKey = commandKey;
    }

    public String getStaticText()
    {
        return StaticText;
    }

    public String[] getList1()
    {
        return list1;
    }

    public String[] getList2()
    {
        return list2;
    }

    public char getCommandKey()
    {
        return commandKey;
    }

    public MyElement(String text, char key, String list1[], String list2[])
    {
        this.commandKey = key;
        this.StaticText = text;
        this.list1 = list1;
        this.list2 = list2;
        initComponents();
    }

    public MyElement()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText(StaticText);
        jLabel2.setText("null");
        jLabel3.setText("null");

        jList1 = new JList<String>(list1);
        jList2 = new JList<String>(list2);

        jList1.addKeyListener(new KeyListener()
        {
            @Override
            public void keyTyped(KeyEvent e)
            {

            }

            @Override
            public void keyPressed(KeyEvent e)
            {
                if (e.getKeyChar() == commandKey)
                    jLabel2.setText(String.valueOf(jList1.getSelectedIndex()));
            }

            @Override
            public void keyReleased(KeyEvent e)
            {

            }
        });
        jList2.addKeyListener(new KeyListener()
        {
            @Override
            public void keyTyped(KeyEvent e)
            {

            }

            @Override
            public void keyPressed(KeyEvent e)
            {
                if (e.getKeyChar() == commandKey)
                    jLabel3.setText(String.valueOf(jList2.getSelectedIndex()));
            }

            @Override
            public void keyReleased(KeyEvent e)
            {

            }
        });

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();

        jScrollPane1.setViewportView(jList1);
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addContainerGap(38, Short.MAX_VALUE))
        );

    }// </editor-fold>//GEN-END:initComponents






    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JList jList1;
    protected javax.swing.JList jList2;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;

    @Override
    public BeanDescriptor getBeanDescriptor()
    {
        return null;
    }

    @Override
    public EventSetDescriptor[] getEventSetDescriptors()
    {
        return new EventSetDescriptor[0];
    }

    @Override
    public int getDefaultEventIndex()
    {
        return 0;
    }

    @Override
    public PropertyDescriptor[] getPropertyDescriptors()
    {
        return new PropertyDescriptor[0];
    }

    @Override
    public int getDefaultPropertyIndex()
    {
        return 0;
    }

    @Override
    public MethodDescriptor[] getMethodDescriptors()
    {
        return new MethodDescriptor[0];
    }

    @Override
    public BeanInfo[] getAdditionalBeanInfo()
    {
        return new BeanInfo[0];
    }

    @Override
    public Image getIcon(int iconKind)
    {
        return null;
    }
    // End of variables declaration//GEN-END:variables

}


